name: Deploy Website (Main + Submodule)

on:
  push:
    branches: [main]
  repository_dispatch:
    types: [trigger-submodule-update]  # <-- triggered by submodule updates

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (with submodules)
        uses: actions/checkout@v4
        with:
          #submodules: true
          submodules: recursive
          fetch-depth: 0

      - name: Update submodules to latest
        run: git submodule update --remote --merge

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload site
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # Include submodule content too

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
